server:
  port: 9000
  servlet:
    context-path: /api/v1

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/footballDb?stringtype=unspecified
    username: nnpia
    password: nnpia
    driverClassName: org.postgresql.Driver
